spring.datasource.url=jdbc:postgresql://dpg-d98fp6mtrd3s73ej8t80-a.singapore-postgres.render.com/expense_manager_w2hs
spring.datasource.username=expense_manager_w2hs_user
spring.datasource.password=hMuNRtcQdoFGQVHyBvMq8mtt1IG1fX1M
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


brevo.api.key=${BREVO_API_KEY}
brevo.from.email=${BREVO_FROM_EMAIL}